apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  IG_FQDN: obdemo.bohocode.forgerock.financial
  RS_FQDN: rs.bohocode.forgerock.financial
  RCS_FQDN: rcs.bohocode.forgerock.financial
