---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

configurations:
- kustomizeConfig.yaml


configMapGenerator:
- name: platform-config
  # The env vars below can be passed into a pod using the envFrom pod spec.
  # These global variables can be used to parameterize your deployments.
  # The FQDN and URLs here should match your ingress or istio gateway definitions
  literals:
  - FQDN=default.bank.example.com # secure banking platform domain
  - IAM_FQDN=default.iplatform.example.com # forgerock identity platform domain
  - CERT_ISSUER="default-issuer" # cert manager issuer. Patch with letsencrypt-prod for LE SSL certs.

generatorOptions:
  disableNameSuffixHash: true

# The variables defined below can be referenced in resources using the syntax $(VARIABLE)
vars:
- name: FQDN
  fieldref:
    fieldpath: data.FQDN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: platform-config
- name: CERT_ISSUER
  fieldref:
    fieldpath: data.CERT_ISSUER
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: platform-config
# TODO: Deprecate the use of $(NAMESPACE) in kustomize configurations
- name: NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: platform-config
  fieldref:
    fieldpath: metadata.namespace