---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
 - github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-config/kustomize/overlay/7.1.0/securebanking/dev?ref=302-remove-kustomize-from-gateway-repo
configurations:
- kustomizeConfig.yaml

configMapGenerator:
  - name: securebanking-platform-config
    behavior: merge
generatorOptions:
  disableNameSuffixHash: true

# The variables defined below can be referenced in resources using the syntax $(VARIABLE)
vars:
- name: IG_FQDN
  fieldref:
    fieldpath: data.IG_FQDN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: securebanking-platform-config
- name: IDENTITY_PLATFORM_FQDN
  fieldref:
    fieldpath: data.IDENTITY_PLATFORM_FQDN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: securebanking-platform-config
- name: INGRESS_IP
  fieldref:
    fieldpath: data.INGRESS_IP
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: securebanking-platform-config
- name: CERT_ISSUER
  fieldref:
    fieldpath: data.CERT_ISSUER
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: securebanking-platform-config
# TODO: Deprecate the use of $(NAMESPACE) in kustomize configurations
- name: NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: securebanking-platform-config
  fieldref:
    fieldpath: metadata.namespace
