apiVersion: v1
kind: ConfigMap
metadata:
  name: securebanking-platform-config
data:
  IG_FQDN: obdemo.dbadham-fr.forgerock.financial
  RS_FQDN: rs.dbadham-fr.forgerock.financial
  RCS_FQDN: rcs.dbadham-fr.forgerock.financial
