namespace: default
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../kustomizeConfig
- ../7.0/ingress
- ../ig

secretGenerator:
- name: obri-ca
  files:
  - ca.crt
generatorOptions:
  disableNameSuffixHash: true
