apiVersion: v1
kind: ConfigMap
metadata:
  name: securebanking-platform-config
data:
  IG_FQDN: obdemo.frlaura-jianu.forgerock.financial
  RS_FQDN: rs.frlaura-jianu.forgerock.financial
  RCS_FQDN: rcs.frlaura-jianu.forgerock.financial
