namespace: obdemo
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../../../base/kustomizeConfig
- ../../../base/forgeops-secrets
- ../../../base/7.0/ds/cts
- ../../../base/7.0/ds/idrepo
- ../../../base/am
- ../../../base/amster
- ../../../base/idm
- ../../../base/end-user-ui
- ../../../base/login-ui
- ../../../base/admin-ui
- ../../../base/7.0/ingress
- ../../../base/ldif-importer
- ../../../base/ig
- ../../../base/obdemo-rcs-ui
- ../../../base/obdemo-rcs-api
- ../../../base/obdemo-rs

secretGenerator:
- name: obri-ca
  files:
  - ca.crt
generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:
  - path: ingress-patch.yaml
    target:
      group: extensions
      kind: Ingress
      name: forgerock
      version: v1beta1
  - path: idm-patch.yaml
    target:
      group: apps
      kind: StatefulSet
      name: idm
      version: v1


patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: platform-config
  data:
    FQDN: obdemo.idhub.cc

- |-
  #Patch AM
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: am
  spec:
    replicas: 1
    template:
      spec:
        containers:
        - name: openam
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 2Gi

- |-
  #Patch IDM
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: idm
  spec:
    replicas: 1
    template:
      spec:
        containers:
        - name: openidm
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 1Gi

- |-
  #Patch DS CTS
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: ds-cts
  spec:
    replicas: 1
    template:
      spec:
        containers:
          - name: ds
            resources:
              requests:
                memory: 500Mi
                cpu: 200m
              limits:
                memory: 500Mi

- |-
  #Patch DS idrepo
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: ds-idrepo
  spec:
    replicas: 1
    template:
      spec:
        containers:
          - name: ds
            resources:
              requests:
                memory: 500Mi
                cpu: 200m
              limits:
                memory: 500Mi

