namespace: default
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../../../base/kustomizeConfig
- ../../../base/7.0/ingress
- ../../../base/ig-local
- ../../../base/obdemo-rcs-ui
- ../../../base/obdemo-rcs-api
- ../../../base/obdemo-rs

secretGenerator:
- name: obri-ca
  files:
  - ca.crt
generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:
  - path: ingress-patch.yaml
    target:
      group: extensions
      kind: Ingress
      name: forgerock
      version: v1beta1

patchesStrategicMerge:
  - configmap.yaml

