# For creating your own custom skaffold profiles we recommend making a copy of this
# file to skaffold-dev.yaml (which is in .gitignore).
# You can "mix and match" diferent services together by creating skaffold profiles
# and by creating a new kustomize profile in kustomize/overlay/
# The default below for skaffold dev is to deploy all services in one shot:
# Note: Upgrade to skaffold/v2alpha3 for skaffold 1.4
apiVersion: skaffold/v1
kind: Config
metadata:
  name: securebanking
## Common YAML anchors
## The yaml anchors are used to make it easier to compose skaffold profiles.
## You should not need to edit this section
.YamlAnchors:

  artifactDefinitions:
    - &IG
      image: ig
      context: docker/7.1.0/ig

    - &OBDEMO-RCS-UI
      image: obdemo-rcs-ui
      context: docker/obdemo-rcs-ui

    - &OBDEMO-RS
      image: obdemo-rs
      context: docker/obdemo-rs

  commonArtifactSets:
    default-artifacts: &default-artifacts
    - *IG
    - *OBDEMO-RCS-UI
    - *OBDEMO-RS

## End YAML Anchors

#---------------------
# Skaffold profiles
#---------------------

# profiles
# add your profile here

profiles:
- name: prod
  build:
    artifacts: *default-artifacts
    tagPolicy:
      sha256: {}
  deploy:
    statusCheckDeadlineSeconds: 600
    kustomize:
      path: ./kustomize/overlay/7.1.0/securebanking/prod

# Default profile
build: &default-build
  artifacts: *default-artifacts
  tagPolicy:
    sha256: {}
deploy: &default-deploy
  statusCheckDeadlineSeconds: 600
  kustomize:
    path: ./kustomize/overlay/7.1.0/securebanking/dev

