apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: obdemo-rcs-ui
  annotations:
    cert-manager.io/cluster-issuer: $(CERT_ISSUER)
spec:
  rules:
  - host: $(FQDN)
    http:
      paths:
      - backend:
          serviceName: obdemo-rcs-ui
          servicePort: 80
        path: /rcs?
  tls:
  - hosts:
    - $(FQDN)
    secretName: sslcert
