apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  IG_FQDN: obdemo.christian-brindley.forgerock.financial
  RS_FQDN: rs.christian-brindley.forgerock.financial
  RCS_FQDN: rcs.christian-brindley.forgerock.financial
