apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  FQDN: obdemo.christian-brindley.forgerock.financial
  IAM_FQDN: iam.dev.forgerock.financial
  RS_FQDN: rs.christian-brindley.forgerock.financial
