apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  FQDN: obdemo.andra-racovita.forgerock.financial
  IAM_FQDN: iam.dev.forgerock.financial
  RS_FQDN: rs.andra-racovita.forgerock.financial
