apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  IG_FQDN: obdemo.andra-racovita.forgerock.financial
  RS_FQDN: rs.andra-racovita.forgerock.financial
  RCS_FQDN: rcs.andra-racovita.forgerock.financial
