apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: slack-notify
spec:
  params:
  - name: message
    type: string
    description: The slack message to notify
    default: "ok"
  stepTemplate:
    env:
    - name: SLACK_FAILED_WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          # TODO: we dont need duplicate webhooks for all tasks
          name: "slack-webhook-smoke"
          key: SLACK_FAILED_WEBHOOK_URL
  steps:
  - name: notify
    # This could be curl, or some slack utility?
    image: gcr.io/cloud-builders/kubectl
    env:
    - name: SLACK_WEBHOOK_URL
      valueFrom:
        secretKeyRef:
          # TODO: we dont need duplicate webhooks for all tasks
          name: "slack-webhook-smoke"
          key: SLACK_WEBHOOK_URL
    script: |
      #!/usr/bin/env bash
      echo "Results $(params.message)"