apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  FQDN: obdemo.dev.forgerock.financial
  IAM_FQDN: iam.dev.forgerock.financial
  AM_REALM: alpha
  IG_CLIENT_ID: ig-client
  IG_CLIENT_SECRET: password
  IG_IDM_USER: service_account.ig
  IG_IDM_PASSWORD: 0penBanking!
  IG_AGENT_ID: ig-agent
  IG_AGENT_PASSWORD: password
  IG_RCS_SECRET: password
  CERT_ISSUER: default-issuer
  ASPSP_KEYSTORE_PATH: /secrets/aspsp.test.p12
  ASPSP_KEYSTORE_PASSWORD: password
  ASPSP_JWTSIGNER_ALIAS: jwtsigner
  ASPSP_JWTSIGNER_KID: R3MviZ4QUPEDJm7RS3Mw
