apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  FQDN: obdemo.dev.forgerock.financial # default.bank.example.com
  IAM_FQDN: iam.dev.forgerock.financial # default.cdk.example.com
  AM_REALM: alpha
  IG_CLIENT_ID: ig-client
  IG_CLIENT_SECRET: password
  IG_IDM_USER: service_user.ig
  IG_IDM_PASSWORD: 0penBanking!
  IG_AGENT_ID: ig-agent
  IG_AGENT_PASSWORD: password
  IG_RCS_SECRET: password
  AM_COOKIE_NAME: replace-with-amcookiename
  CERT_ISSUER: default-issuer
