apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  FQDN: default.bank.example.com
  IAM_FQDN: openam-solutionarchitecture-hlobpoc.forgeblocks.com #default.cdk.example.com
  AM_REALM: alpha
  IG_CLIENT_ID: ig-client
  IG_CLIENT_SECRET: password
  IG_IDM_USER: service_user.ig
  IG_IDM_PASSWORD: 0penBanking!
  IG_AGENT_ID: ig-agent
  IG_AGENT_PASSWORD: password