namespace: default
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../../../../base/obdemo-bank

patchesJson6902:
  - path: ingress-patch.yaml
    target:
      group: extensions
      kind: Ingress
      name: forgerock
      version: v1beta1
  - path: deployment-patch.yaml
    target:
      group: apps
      kind: Deployment
      name: ig
      version: v1

patchesStrategicMerge:
  - configmap.yaml
