namespace: ig
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../../../../base/obdemo-bank

patchesJson6902:
  - path: secrets-prometheus-patch.yaml
    target:
      kind: Secret
      name: openig-secrets-env
      version: v1

patchesStrategicMerge:
  - configmap.yaml
