namespace: dev
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../../../../base/obdemo-bank

patchesJson6902:
  - path: secrets-prometheus-patch.yaml
    target:
      kind: Secret
      name: openig-secrets-env
      version: v1

patchesStrategicMerge:
  - configmap.yaml

images:
- name: ig
  newName: eu.gcr.io/sbat-gcr-release/securebanking/gate/ig
  newTag: latest
- name: obdemo-rcs-ui
  newName: eu.gcr.io/sbat-gcr-develop/securebanking/gate/obdemo-rcs-ui
  newTag: latest
- name: obdemo-rs
  newName: eu.gcr.io/sbat-gcr-develop/securebanking/gate/obdemo-rs
  newTag: latest