apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  IG_FQDN: obdemo.mariantiris.forgerock.financial
  RS_FQDN: rs.mariantiris.forgerock.financial
  RCS_FQDN: rcs.mariantiris.forgerock.financial
