apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  FQDN: obdemo.mariantiris.forgerock.financial
  IAM_FQDN: iam.dev.forgerock.financial
  RS_FQDN: rs.mariantiris.forgerock.financial
