namespace: jamie
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../../../../base/kustomizeConfig
- ../../../../base/7.0/ingress
- ../../../../base/ig

patchesStrategicMerge:
  - configmap.yaml

images:
- name: ig
  newName: eu.gcr.io/sbat-gcr-release/securebanking/gate/ig
  newTag: latest
- name: obdemo-rcs-ui
  newName: eu.gcr.io/sbat-gcr-develop/securebanking/gate/obdemo-rcs-ui
  newTag: latest
- name: obdemo-rs
  newName: eu.gcr.io/sbat-gcr-develop/securebanking/gate/obdemo-rs
  newTag: latest