apiVersion: apps/v1
kind: Deployment
metadata:
  name: ig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ig
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: ig
    spec:
      initContainers:
      - name: iam-init
        image: eu.gcr.io/sbat-gcr-develop/securebanking/secureopenbanking-uk-fidc-initializer:latest
        imagePullPolicy: Always
        env:
        - name: OPEN_AM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: am-env-secrets
              key: AM_PASSWORDS_AMADMIN_CLEAR
        - name: IAM_FQDN
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: IAM_FQDN
        - name: REQUEST_BODY_PATH
          value: config/
        command: ["/bin/sh", "-c"]
        args: 
          - |
            until $(curl -X GET --output /dev/null --silent --head --fail -H "X-OpenIDM-Username: anonymous" \
            -H "X-OpenIDM-Password: anonymous" -H "X-OpenIDM-NoSession: true" \
            https://$IAM_FQDN/openidm/info/ping)
            do
            echo "IDM not ready"
            sleep 10
            done
            ./setup
      containers:
      - name: ig
        env:
        # - name: OPENIG_BASE
        #   value: /config
        # - name: CATALINA_OPTS
        #   value: -server
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - secretRef:
            name: openig-secrets-env
        - configMapRef:
            name: platform-config
        #image: gcr.io/forgerock-io/ig/docker-build:7.0.0-af5592b
        image: ig
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /kube/liveness
            port: 8080
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /kube/readiness
            port: 8080
          initialDelaySeconds: 5
        ports:
        - containerPort: 8080   
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
