apiVersion: v1
kind: Secret
metadata:
  name: openig-secrets-env
type: Opaque
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: am-env-secrets
  annotations:
    replicator.v1.mittwald.de/replicate-from: cdk/am-env-secrets
type: Opaque
data: {}
