namespace: nightly
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../../../../base/obdemo-bank

patchesStrategicMerge:
  - configmap.yaml

images:
- name: ig
  newName: eu.gcr.io/sbat-gcr-release/securebanking/gate/ig
  newTag: latest
  