- op: replace
  path: /spec/rules
  value:
    - host: $(FQDN)
      http:
        paths:
        - backend:
            serviceName: ig
            servicePort: 8080
          path: /am
        - backend:
            serviceName: ig
            servicePort: 8080
          path: /rcs-api
