namespace: default
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../../../../base/obdemo-bank

patchesJson6902:
  - path: ingress-patch.yaml
    target:
      group: extensions
      kind: Ingress
      name: forgerock
      version: v1beta1

patchesStrategicMerge:
  - configmap.yaml
