---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  BASE_FQDN: {{ .Values.authorizationServer.baseFqdn | quote }}
  AS_FQDN: {{ .Values.authorizationServer.fqdn | quote }}
  AM_REALM: {{ .Values.authorizationServer.realm | quote }}
  IDENTITY_PLATFORM_FQDN: {{ .Values.identityPlatform.fqdn | quote }}
  CLOUD_TYPE: {{ .Values.identityPlatform.type | quote }}
  RS_FQDN: {{ .Values.resourceServer.fqdn | quote }}
  RS_MTLS_FQDN: {{ .Values.resourceServer.mtlsFqdn | quote }}
  GATEWAY_DATA_REPO_URI: {{ .Values.resourceServer.gatewayDataRepoUri | quote }}
  USER_OBJECT: {{ .Values.resourceServer.userObject | quote }}
  IG_OB_ASPSP_SIGNING_KEYSTORE_ALIAS: {{ .Values.resourceServer.ob.signingKeystore.alias | quote }}
  IG_OB_ASPSP_SIGNING_KEYSTORE_PATH: {{ .Values.resourceServer.ob.signingKeystore.path | quote }}
  IG_OB_ASPSP_SIGNING_KEYSTORE_TYPE: {{ .Values.resourceServer.ob.signingKeystore.type | quote }}
  IG_OB_ASPSP_SIGNING_KID: {{ .Values.resourceServer.ob.signingKeystore.kid | quote }}
  OB_ASPSP_ORG_ID: {{ .Values.resourceServer.ob.aspsp.orgId | quote }}
  OB_ASPSP_SOFTWARE_ID: {{ .Values.resourceServer.ob.aspsp.softwareId | quote }}
  RCS_API_INTERNAL_SVC: {{ .Values.resourceServer.ob.rcs.apiInternalSvc | quote }}
  RCS_CONSENT_RESPONSE_JWT_ISSUER: {{ .Values.resourceServer.ob.rcs.consentResponseJwtIssuer | quote }}
  RCS_CONSENT_RESPONSE_JWT_SIGNINGKEYID: {{ .Values.resourceServer.ob.rcs.consentResponseJwtSigningKeyId | quote }}
  RCS_CONSENT_STORE_URI: {{ .Values.resourceServer.ob.rcs.consentStoreUri | quote }}
  RCS_UI_INTERNAL_SVC: {{ .Values.resourceServer.ob.rcs.uiInternalSvc | quote }}
  RS_API_URI: {{ .Values.resourceServer.ob.api.uri | quote }}
  RS_INTERNAL_SVC: {{ .Values.resourceServer.ob.api.internalSvc | quote }}
{{- if eq .Values.identityPlatform.type "FIDC" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-aic-config
data:
  IDENTITY_DEFAULT_USER_AUTHENTICATION_SERVICE: {{ .Values.aic.identityDefaultUserAuthenticationService | quote }}
  IDENTITY_GOOGLE_SECRET_STORE_NAME: {{ .Values.aic.identityGoogleSecretStoreName | quote }}
  IDENTITY_GOOGLE_SECRET_STORE_OAUTH2_CA_CERTS_SECRET_NAME: {{ .Values.aic.identityGoogleSecretStoreOAuth2CACertsSecretName | quote }}
{{- end }}
