---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  IG_CLIENT_ID: {{ .Values.resourceServer.oauth2Client.id }}
  IG_CLIENT_SECRET: {{ .Values.resourceServer.oauth2Client.secret }}
  IG_IDM_USER: {{ .Values.resourceServer.idm.user }}
  IG_IDM_PASSWORD: {{ .Values.resourceServer.idm.password }}
  IG_AGENT_ID: {{ .Values.resourceServer.agent.id }}
  IG_AGENT_PASSWORD: {{ .Values.resourceServer.agent.password }}
  IG_OB_ASPSP_SIGNING_KEYSTORE_STOREPASS: {{ .Values.resourceServer.ob.signingKeystore.storepass }}
  IG_OB_ASPSP_SIGNING_KEYSTORE_KEYPASS: {{ .Values.resourceServer.ob.signingKeystore.keypass }}
  MONGODB_TEST_FACILITY_USERNAME: {{ .Values.mongodb.testFacility.username }}
  MONGODB_TEST_FACILITY_PASSWORD: {{ .Values.mongodb.testFacility.password }}
  MONGODB_CONSENT_USERNAME: {{ .Values.mongodb.consent.username }}
  MONGODB_CONSENT_PASSWORD: {{ .Values.mongodb.consent.password }}
