namespace: ig
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../../../../base/7.0/ingress
- ../../../../base/7.0/am
- ../../../../base/ig
- ../../../../base/kustomizeConfig

patchesJson6902:
  - path: ingress-patch.yaml
    target:
      group: extensions
      kind: Ingress
      name: forgerock
      version: v1beta1
  - path: deployment-patch.yaml
    target:
      group: apps
      kind: Deployment
      name: ig
      version: v1
  - path: secrets-prometheus-patch.yaml
    target:
      kind: Secret
      name: openig-secrets-env
      version: v1

patchesStrategicMerge:
  - configmap.yaml

images:
- name: ig
  newName: eu.gcr.io/sbat-gcr-develop/securebanking/gate/ig
  newTag: latest
