name: merge

on:
  push:
    branches: [ master ]

env:
  SERVICE_NAME: ig
  GIT_SHA_SHORT: $(echo ${{ github.sha }} | cut -c1-7)

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker

      - uses: actions/setup-java@v3
        id: maven
        name: set java and maven cache
        with:
          distribution: 'adopt'
          java-version: '17'
          architecture: x64
          cache: 'maven'

      - name: Build maven
        run: |
          mvn clean deploy -DaltDeploymentRepository=release::default::"https://${{ secrets.FR_ARTIFACTORY_USER }}:${{ secrets.FR_ARTIFACTORY_TOKEN }}@maven.forgerock.org/artifactory/community/"

      - name: docker build
        run: |
          make build-docker-ig tag=${{ env.GIT_SHA_SHORT }} env="prod"
          docker tag eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking/gate/${{ env.SERVICE_NAME }}:${{ env.GIT_SHA_SHORT }} \
          eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking/gate/${{ env.SERVICE_NAME }}:latest
          docker push --all-tags eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking/gate/${{ env.SERVICE_NAME }}

      - name: 'run functional tests'
        uses: codefresh-io/codefresh-pipeline-runner@master
        with:
          args: '-v SERVICE_NAME=${{ env.SERVICE_NAME }}'
        env:
          PIPELINE_NAME: 'ForgeCloud/sbat-infra/service-build'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          TRIGGER_NAME: github-actions-trigger-gateway
        id: run-pipeline
