name: merge

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_KEY }}
          export_default_credentials: true
        # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker
      
      - name: docker build
        run: |
          make build-docker-ig tag=${{ github.sha }}
          make build-docker-ig gcr-repo=${{ secrets.RELEASE_REPO }} 
