name: Pull Request Build and Deploy

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  PR_NUMBER: pr-${{ github.event.number }}
  SERVICE_NAME: ig

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Create lowercase Github Username
        id: github_username
        run: echo "GITHUB_USER=$(echo ${{github.actor}} | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_OUTPUT}
      
      - name: Checkout Code
        uses: actions/checkout@v3

      # set java and cache
      - name: Set Java and Maven Cache
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          architecture: x64
          cache: 'maven'
          server-id: forgerock-private-releases # protected release repo
          server-username: FR_ARTIFACTORY_USER # env variable for username to authentication protected repo
          server-password: FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD # env variable encrypted password to authentication protected repo

      - name: Build maven
        run: |
          mvn clean install
        env:
          FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
          FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}
        
      - name: Auth to GCP  
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DEV_GAR_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1

        # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Auth Docker
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: Build Docker Image
        run: |
          # Create development mode docker image
          make docker tag=$PR_NUMBER env="dev"
          # Create production mode docker image
          make docker tag="$PR_NUMBER-prod"

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: build
    #if: github.actor != 'dependabot[bot]'
    if: ${{ steps.github_username.outputs.GITHUB_USER }}!= 'shaunharrisonfr'
    steps:       
      - name: 'Update Environment'
        uses: codefresh-io/codefresh-pipeline-runner@master
        with:
          args: '-v TAG=${{ env.PR_NUMBER }} -v SERVICE_NAME=${{ env.SERVICE_NAME }} -v ENVIRONMENT=${{ env.GITHUB_USER }}'
        env:
          PIPELINE_NAME: 'ForgeCloud/sbat-infra/service-build'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          TRIGGER_NAME: github-actions-trigger-gateway