name: Rebase
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  run_rebase-template:
    name: Rebase
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/merge-branch.yml@main
    secrets: inherit
    with:
      componentName: secure-api-gateway-fapi-pep-rs-ob
      sourceBranch: main
      targetBranch: ob-v4