name: Publish package to the ForgeRock artifactory
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Deploy release
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Build maven
        run: |
          mvn clean install

      - name: Build Docker Image
        run: |
          make docker tag=${{ github.event.release.tag_name }} gcr-repo=${{ secrets.RELEASE_REPO }}
